### PR TITLE
[T-6337][15.0][ADD] ecommerce_connector_sale_order_type: sale order type for ecommerce sale orders

### PR DESCRIPTION
**Pull request by manuelregidor**
@luis-ron @ValentinVinagre @HaraldPanten 

@Tisho99 Could you review, please?

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@manuelregidor I would set ecommerce_connector_sale_order_type. Why sale_type instead of sale_order_type?

**Comment by manuelregidor** [comment]
@HaraldPanten I select that name so it's not too long. Let me know if you want me to change it.

**Review by Tisho99 — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
@manuelregidor 

IMO we should consider the full name because you're combining the ecommerce_connector with a sale_order_type extension. We'll add only "_order", so I think we can assume this extra text in the module name.

Sorry for being picky with that 🙏

**Comment by manuelregidor** [comment]
@HaraldPanten Module name changed.

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
