### PR TITLE
[T-4718][14.0][ADD] ecommerce_connector_sii: Set the invoice as Simplified if the customer has no VAT

### PR DESCRIPTION
**Pull request by manuelregidor**
@HaraldPanten @ValentinVinagre 

This module avoids the dependency of the module ecommerce_connector towards l10n_es_aeat_sii_oca.

T-4718

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@manuelregidor 
The name of the module does not match the functionality of the module. The module is called "ecommerce_connector_sii" so it acts as a bridge with the "ecommerce_connector" and the "l10n_es_aeat_sii_oca". But I don't understand why it focuses on whether it is simplified or not. In principle, it doesn't provide communication to use it with the SII at a general level?

**Comment by manuelregidor** [comment]
@ValentinVinagre The thing is that the field sii_simplified_invoice in res.partner is created by the module l10n_es_aeat_sii_oca, and that's why I chose that name. I guess I could replace it with something line "ecommerce_connector_simplified_invoice". WDYT?

**Comment by ValentinVinagre** [comment]
but it only serves to use whether it is simplified or not in the yes? And if you use the SII, which module is installed?
There's something weird about the name. It would have to be called "ecommerce_connector_sii" but not only refer to the simplified billing of the sii. You would have to review the readme, module name in the manifest, etc.

**Comment by manuelregidor** [comment]
@ValentinVinagre README and description modified. Could you review? Thank you

**Pull request merged**
